var data = require("users/irtharles/gpw-view-tool:data.js");

// Carregar as imagens
var images = data.loadImages();

var LAYERS = [
  {
    key: "esa_worldcover_v2_2020",
    layerName: "ESA WorldCover v2 2020",
    imagem: images.worldCoverV2,
    visible: true,
    bands: ["Map"],
    palette: [
      "006400",
      "ffbb22",
      "ffff4c",
      "f096ff",
      "fa0000",
      "b4b4b4",
      "f0f0f0",
      "0064c8",
      "0096a0",
      "00cf75",
      "fae6a0",
    ],
    classNames: [
      "Tree cover",
      "Shrubland",
      "Grassland",
      "Cropland",
      "Built-up",
      "Bare / sparse vegetation",
      "Snow and ice",
      "Permanent water bodies",
      "Herbaceous wetland",
      "Mangroves",
      "Moss and lichen",
    ],
    imagemDictDataset: {
      10: "Tree cover",
      20: "Shrubland",
      30: "Grassland",
      40: "Cropland",
      50: "Built-up",
      60: "Bare / sparse vegetation",
      70: "Snow and ice",
      80: "Permanent water bodies",
      90: "Herbaceous wetland",
      95: "Mangroves",
      100: "Moss and lichen",
    },
  },
  {
    key: "gpw_2020",
    layerName: "Global Pasture Watch 2020",
    imagem: images.gpw2020,
    visible: true,
    bands: [],
    palette: ["ffd700", "ffa500"],
    classNames: ["Cultivated grassland", "Natural/semi-natural grassland"],
    imagemDictDataset: {
      1: "Cultivated grassland",
      2: "Natural/Semi-Natural grassland",
    },
  },
  {
    key: "glc_fcs_2020",
    layerName: "GLC-FCS30D 2020",
    imagem: images.glcfcsRecode,
    visible: true,
    bands: [],
    palette: [
      "ffff64",
      "ffff64",
      "ffff00",
      "aaf0f0",
      "4c7300",
      "006400",
      "a8c800",
      "00a000",
      "005000",
      "003c00",
      "286400",
      "285000",
      "a0b432",
      "788200",
      "966400",
      "964b00",
      "966400",
      "ffb432",
      "ffdcd2",
      "ffebaf",
      "ffd278",
      "ffebaf",
      "00a884",
      "73ffdf",
      "9ebb3b",
      "828282",
      "f57ab6",
      "66cdab",
      "444f89",
      "c31400",
      "fff5d7",
      "dcdcdc",
      "fff5d7",
      "0046c8",
      "ffffff",
      "ffffff",
      "ffffff",
    ],
    classNames: [
      "Rainfed cropland",
      "Herbaceous cover cropland",
      "Tree or shrub cover (Orchard) cropland",
      "Irrigated cropland",
      "Open evergreen broadleaved forest",
      "Closed evergreen broadleaved forest",
      "Open deciduous broadleaved forest (0.15<fc<0.4)",
      "Closed deciduous broadleaved forest (fc>0.4)",
      "Open evergreen needle-leaved forest (0.15< fc <0.4)",
      "Closed evergreen needle-leaved forest (fc >0.4)",
      "Open deciduous needle-leaved forest (0.15< fc <0.4)",
      "Closed deciduous needle-leaved forest (fc >0.4)",
      "Open mixed leaf forest (broadleaved and needle-leaved)",
      "Closed mixed leaf forest (broadleaved and needle-leaved)",
      "Shrubland",
      "Evergreen shrubland",
      "Deciduous shrubland",
      "Grassland",
      "Lichens and mosses",
      "Sparse vegetation (fc<0.15)",
      "Sparse shrubland (fc<0.15)",
      "Sparse herbaceous (fc<0.15)",
      "Swamp",
      "Marsh",
      "Flooded flat",
      "Saline",
      "Mangrove",
      "Salt marsh",
      "Tidal flat",
      "Impervious surfaces",
      "Bare areas",
      "Consolidated bare areas",
      "Unconsolidated bare areas",
      "Water body",
      "Permanent ice and snow",
      "Filled value",
    ],
    imagemDictDataset: {
      10: "Rainfed cropland",
      11: "Herbaceous cover cropland",
      12: "Tree or shrub cover (Orchard) cropland",
      20: "Irrigated cropland",
      51: "Open evergreen broadleaved forest",
      52: "Closed evergreen broadleaved forest",
      61: "Open deciduous broadleaved forest (0.15<fc<0.4)",
      62: "Closed deciduous broadleaved forest (fc>0.4)",
      71: "Open evergreen needle-leaved forest (0.15< fc <0.4)",
      72: "Closed evergreen needle-leaved forest (fc >0.4)",
      81: "Open deciduous needle-leaved forest (0.15< fc <0.4)",
      82: "Closed deciduous needle-leaved forest (fc >0.4)",
      91: "Open mixed leaf forest (broadleaved and needle-leaved)",
      92: "Closed mixed leaf forest (broadleaved and needle-leaved)",
      120: "Shrubland",
      121: "Evergreen shrubland",
      122: "Deciduous shrubland",
      130: "Grassland",
      140: "Lichens and mosses",
      150: "Sparse vegetation (fc<0.15)",
      152: "Sparse shrubland (fc<0.15)",
      153: "Sparse herbaceous (fc<0.15)",
      181: "Swamp",
      182: "Marsh",
      183: "Flooded flat",
      184: "Saline",
      185: "Mangrove",
      186: "Salt marsh",
      187: "Tidal flat",
      190: "Impervious surfaces",
      200: "Bare areas",
      201: "Consolidated bare areas",
      202: "Unconsolidated bare areas",
      210: "Water body",
      220: "Permanent ice and snow",
      0: "Filled value",
    },
  },
  {
    key: "glad_lclu_2020",
    layerName: "GLAD LCLU 2020",
    imagem: images.GLCLU2020,
    visible: true,
    bands: [],
    palette: [
      "FAFAC3",
      "E0E081",
      "B0B006",
      "065106",
      "B7BDC2",
      "73A7D6",
      "0986F7",
      "3B7C81",
      "1147DD",
      "ffffff",
      "ff7d00",
      "64dcdc",
      "111133",
    ],
    classNames: [
      "Terra Firma - True desert",
      "Terra Firma - Semi-arid",
      "Terra Firma - Dense short vegetation",
      "Terra Firma - Tree cover",
      "Wetland - Salt pan",
      "Wetland - Sparse vegetation",
      "Wetland - Dense short vegetation",
      "Wetland - Tree cover",
      "Open surface water",
      "Snow/ice",
      "Cropland",
      "Built-up",
      "Ocean",
    ],
    imagemDictDataset: {
      1: "Terra Firma - True desert",
      2: "Terra Firma - Semi-arid",
      3: "Terra Firma - Dense short vegetation",
      4: "Terra Firma - Tree cover",
      5: "Wetland - Salt pan",
      6: "Wetland - Sparse vegetation",
      7: "Wetland - Dense short vegetation",
      8: "Wetland - Tree cover",
      9: "Open surface water",
      10: "Snow/ice",
      11: "Cropland",
      12: "Built-up",
      13: "Ocean",
    },
  },
];

exports.LAYERS = LAYERS;
